// Amostra pública autoral, independente do conteúdo pago.
const stages=[
 ['Objetivo e contrato','Você vai entregar um relatório de vendas que outra pessoa consegue recriar. Comece pelo resultado, não pela escolha de uma ferramenta. O projeto usa somente biblioteca padrão Python e dados fictícios.','Baixe e extraia o kit. Abra a pasta no seu editor. Leia README.md e CONTRATO.md. Identifique o arquivo de entrada e o comando de validação.','Leia README.md e CONTRATO.md. Explique a tarefa, os arquivos e como conferir o resultado. Não edite ainda.',['O contrato foi lido.','Sei localizar vendas.csv e verificar.py.']],
 ['Baseline: veja o problema','Reproduzir a falha antes da correção ajuda a provar que você resolveu o problema certo. O kit começa com uma função incompleta; isso é o exercício. Um erro de ambiente é diferente de uma falha do contrato.','Execute python verificar.py (ou python3 verificar.py). Registre a mensagem inicial. Se Python não existir, instale pelo site oficial antes de continuar.','O comando python verificar.py falhou. Vou colar o erro sem dados pessoais. Explique a causa e separe problema de ambiente de função não implementada.',['Registrei o comando e o erro inicial.','Não alterei o verificador para ocultar a falha.']],
 ['Dados: calcule o esperado','Há seis vendas. Três devem ser rejeitadas: uma repetida, uma com data impossível e uma com quantidade negativa. Somar dinheiro em centavos evita ambiguidade de arredondamento.','Calcule à mão: 2×2500 + 3950 + 4×1000 = 12950 centavos. Compare com o contrato. Anote por que cada linha inválida foi rejeitada.','Explique cada linha de vendas.csv conforme CONTRATO.md. Confirme o total esperado e os motivos de rejeição. Não edite os dados nem o gabarito.',['Calculei 12950 centavos.','Identifiquei as rejeições das linhas 4, 5 e 6.']],
 ['IA: implemente uma mudança','Um pedido útil informa arquivo, regras, limites e aceite. A IA deve ajudar você a produzir uma função verificável. Revise os arquivos e não aceite alterar o teste para declarar sucesso.','Peça a implementação de processar em pipeline.py. Use seu Codex, Claude ou outra ferramenta. Revise o diff antes de executar.','Implemente processar(origem,destino) em pipeline.py conforme CONTRATO.md. Use somente biblioteca padrão. Preserve verificar.py e vendas.csv. Valide ID único, data real, quantidade positiva e centavos não negativos. Escreva relatorio.json com receita_centavos, aceitas e rejeitadas (linha e motivo). Rode python verificar.py e relate o resultado real.',['Somente os arquivos previstos foram alterados.','A função produz o JSON do contrato.']],
 ['Validação: confira o resultado','Executar o verificador produz evidência. Uma mensagem da IA dizendo “passou” sem comando e saída não basta. O verificador testa receita, contagens, rejeições, origem imutável e repetição.','Execute python verificar.py. Se falhar, leve o erro à IA e peça uma correção pequena. Repita até obter PASSOU. Anote o comando e a saída.','Revise a falha do verificador sem editar verificar.py. Corrija a implementação e execute novamente. Explique o comportamento corrigido e mostre a saída verdadeira.',['Executei o verificador e registrei a saída.','A origem permanece igual e a saída é determinística.']],
 ['Revisão: teste uma hipótese diferente','O aceite da amostra não cobre todo arquivo possível. Uma entrega honesta explicita o limite e testa algo além do exemplo. Um caso vazio ou uma coluna ausente revela suposições escondidas.','Peça testes adicionais para CSV vazio, data impossível e cabeçalho incompleto. Execute os testes e registre o que o programa suporta e o que falta.','Crie testes adicionais separados do verificador: entrada vazia, data impossível e cabeçalho incompleto. Revise tratamento de erros e explique as limitações. Não declare suporte sem executar.',['Testei pelo menos um caso adicional.','Registrei limitações observadas.']],
 ['Entrega: outra pessoa consegue usar?','A documentação deve ligar o objetivo à versão do código e aos comandos. Recriar em pasta nova testa dependências esquecidas. O resultado é um pequeno produto de dados, não uma conversa com a IA.','Preencha ENTREGA.md com resultado, decisões, comandos, limites e reversão. Copie a solução para uma pasta nova com o kit e rode verificar.py. Faça commit no seu repositório de estudo se usar Git.','Revise README.md e ENTREGA.md para outra pessoa reproduzir. Liste dependências, comando, saída esperada, limitações e como retornar à versão anterior. Preserve evidências reais.',['A reprodução em pasta nova foi conferida.','ENTREGA.md documenta resultado e limitações.']],
 ['Dossiê: conclua e escolha o próximo nó','Agora você tem objetivo, contrato, baseline, código, validação e documentação. Esta amostra completa permite experimentar o método antes da assinatura. O registro é autodeclarado; não é certificação nem correção automática por IA.','Exporte o dossiê e guarde junto da sua solução. Para continuar em projetos avançados de produto, agentes e MCPs com progresso por conta, escolha um plano da Academy.','Faça uma revisão final de CONTRATO.md, código, testes e ENTREGA.md. Compare com o objetivo inicial. Informe o que foi entregue, validado e ficou pendente.',['Guardei código, testes e dossiê.','Sei explicar a entrega sem depender da resposta da IA.']]
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='datano-free-delivery-v1';let state={stage:0,evidence:{},completed:[],tool:'Codex'};
try{const s=JSON.parse(localStorage.getItem(key));if(s&&typeof s==='object'){state.stage=Number.isInteger(s.stage)&&s.stage>=0&&s.stage<8?s.stage:0;state.completed=Array.isArray(s.completed)?[...new Set(s.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<8))]:[];state.evidence=Object.fromEntries(Object.entries(s.evidence||{}).filter(([k,v])=>/^[0-7]$/.test(k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,5000)]));state.tool=['Codex','Claude','Outra ferramenta'].includes(s.tool)?s.tool:'Codex';}}catch{}
const target=document.querySelector('#free-delivery');
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true;}catch{return false;}}
function render(){if(!target)return;const s=stages[state.stage];target.innerHTML=`<div class="section-heading"><div><span class="eyebrow">AMOSTRA COMPLETA · SEM CADASTRO</span><h2>Da conversa com IA à sua primeira entrega.</h2></div></div><p>Construa um pipeline de vendas fictícias, corrija erros com IA e entregue um relatório que dá para conferir. Reserve 60–90 minutos. Requisitos: Python 3.10+, editor e sua ferramenta de IA. Os planos de IA seguem o fornecedor escolhido.</p><div class="delivery-actions"><a class="button primary" href="starter-kit.zip" download>Baixar kit de prática ↓</a><label>Sua ferramenta<select id="delivery-tool">${['Codex','Claude','Outra ferramenta'].map(t=>`<option ${state.tool===t?'selected':''}>${t}</option>`).join('')}</select></label></div><p>${state.completed.length} de 8 etapas concluídas neste navegador</p><div class="delivery-layout"><nav aria-label="Etapas da amostra">${stages.map((x,i)=>`<button data-delivery-stage="${i}" aria-current="${i===state.stage?'step':'false'}"><span>${state.completed.includes(i)?'✓':String(i+1).padStart(2,'0')}</span>${esc(x[0])}</button>`).join('')}</nav><section class="delivery-stage"><span class="eyebrow">NÓ ${state.stage+1} / 8</span><h3>${esc(s[0])}</h3><p>${esc(s[1])}</p><h4>Faça no seu ambiente</h4><p>${esc(s[2])}</p><details><summary>Prompt para ${esc(state.tool)}</summary><pre id="delivery-prompt">${esc(s[3])}</pre></details><button class="button ghost" id="delivery-copy">Copiar prompt →</button><form id="delivery-evidence"><label>Evidência da sua execução<textarea name="evidence" rows="4" maxlength="5000" placeholder="Registre comando, resultado e arquivo. Não inclua senhas ou dados pessoais.">${esc(state.evidence[state.stage]||'')}</textarea></label><fieldset><legend>Confira o aceite</legend>${s[4].map(c=>`<label class="delivery-check"><input type="checkbox" required ${state.completed.includes(state.stage)?'checked':''}>${esc(c)}</label>`).join('')}</fieldset><button class="button primary">Salvar etapa e continuar →</button></form><p id="delivery-feedback" role="status"></p></section></div><div class="delivery-finish"><div><h3>${state.completed.length===8?'Sua amostra está concluída. Qual será a próxima entrega?':'Guarde as evidências da sua jornada.'}</h3><p>Exporte o dossiê a qualquer momento. A assinatura abre os projetos avançados e o progresso salvo na sua conta.</p><button class="button ghost" id="delivery-export">Exportar dossiê ↓</button></div><a class="button primary" href="https://academy.datano.com.br/#planos">Continuar na Academy · Assinar ↗</a></div><p class="public-note">O progresso é autodeclarado e fica neste navegador. A página prepara prompts; a IA e os comandos são executados no seu ambiente. Nenhuma chamada de IA ocorre ao abrir a jornada.</p>`;}
if(target){render();target.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.deliveryStage!==undefined){state.stage=Number(b.dataset.deliveryStage);save();render();}if(b.id==='delivery-copy'){try{await navigator.clipboard.writeText(stages[state.stage][3]);document.querySelector('#delivery-feedback').textContent='Prompt copiado. Use no seu ambiente.';}catch{document.querySelector('#delivery-feedback').textContent='Abra o prompt e copie manualmente.';}}if(b.id==='delivery-export'){const md=['# Minha primeira entrega com IA — DatanO',`Ferramenta: ${state.tool}`,`Data: ${new Date().toISOString()}`,'Registro autodeclarado.'].concat(stages.map((s,i)=>`## ${s[0]}\nEstado: ${state.completed.includes(i)?'Concluído pelo aluno':'Pendente'}\nAceite:\n${s[4].map(c=>'- '+c).join('\n')}\nEvidência: ${state.evidence[i]||'Não registrada.'}`)).join('\n\n');const url=URL.createObjectURL(new Blob([md],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='minha-entrega-datano.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
 target.addEventListener('change',e=>{if(e.target.id==='delivery-tool'){state.tool=e.target.value;save();render();}});
 target.addEventListener('submit',e=>{if(e.target.id!=='delivery-evidence')return;e.preventDefault();const evidence=String(new FormData(e.target).get('evidence')).trim();if(evidence.length<30){document.querySelector('#delivery-feedback').textContent='Descreva a evidência em pelo menos 30 caracteres.';return;}state.evidence[state.stage]=evidence;state.completed=[...new Set([...state.completed,state.stage])];state.stage=Math.min(state.stage+1,7);const stored=save();render();document.querySelector('#delivery-feedback').textContent=stored?'Etapa registrada. Continue sua entrega.':'Armazenamento indisponível: exporte seu dossiê para preservar o progresso.';});
}
