import {stepProgress,stateLabels,copyText} from './learning-ui.js';
import {connectJourney} from './learning-account.js';
let cloud;
// Amostra pública autoral, independente do conteúdo pago.
const technicalStages=[
 ['Objetivo e contrato','Você vai entregar um relatório de vendas que outra pessoa consegue recriar. Comece pelo resultado, não pela escolha de uma ferramenta. O projeto usa somente biblioteca padrão Python e dados fictícios.','Baixe e extraia o kit. Abra a pasta no seu editor. Leia README.md e CONTRATO.md. Identifique o arquivo de entrada e o comando de validação.','Leia README.md e CONTRATO.md. Explique a tarefa, os arquivos e como conferir o resultado. Não edite ainda.',['O contrato foi lido.','Sei localizar vendas.csv e verificar.py.']],
 ['Baseline: veja o problema','Reproduzir a falha antes da correção ajuda a provar que você resolveu o problema certo. O kit começa com uma função incompleta; isso é o exercício. Um erro de ambiente é diferente de uma falha do contrato.','Execute python verificar.py (ou python3 verificar.py). Registre a mensagem inicial. Se Python não existir, instale pelo site oficial antes de continuar.','O comando python verificar.py falhou. Vou colar o erro sem dados pessoais. Explique a causa e separe problema de ambiente de função não implementada.',['Registrei o comando e o erro inicial.','Não alterei o verificador para ocultar a falha.']],
 ['Dados: calcule o esperado','Há seis vendas. Três devem ser rejeitadas: uma repetida, uma com data impossível e uma com quantidade negativa. Somar dinheiro em centavos evita ambiguidade de arredondamento.','Calcule à mão: 2×2500 + 3950 + 4×1000 = 12950 centavos. Compare com o contrato. Anote por que cada linha inválida foi rejeitada.','Explique cada linha de vendas.csv conforme CONTRATO.md. Confirme o total esperado e os motivos de rejeição. Não edite os dados nem o gabarito.',['Calculei 12950 centavos.','Identifiquei as rejeições das linhas 4, 5 e 6.']],
 ['IA: implemente uma mudança','Um pedido útil informa arquivo, regras, limites e aceite. A IA deve ajudar você a produzir uma função verificável. Revise os arquivos e não aceite alterar o teste para declarar sucesso.','Peça a implementação de processar em pipeline.py. Use seu Codex, Claude ou outra ferramenta. Revise o diff antes de executar.','Implemente processar(origem,destino) em pipeline.py conforme CONTRATO.md. Use somente biblioteca padrão. Preserve verificar.py e vendas.csv. Valide ID único, data real, quantidade positiva e centavos não negativos. Escreva relatorio.json com receita_centavos, aceitas e rejeitadas (linha e motivo). Rode python verificar.py e relate o resultado real.',['Somente os arquivos previstos foram alterados.','A função produz o JSON do contrato.']],
 ['Validação: confira o resultado','Executar o verificador produz evidência. Uma mensagem da IA dizendo “passou” sem comando e saída não basta. O verificador testa receita, contagens, rejeições, origem imutável e repetição.','Execute python verificar.py. Se falhar, leve o erro à IA e peça uma correção pequena. Repita até obter PASSOU. Anote o comando e a saída.','Revise a falha do verificador sem editar verificar.py. Corrija a implementação e execute novamente. Explique o comportamento corrigido e mostre a saída verdadeira.',['Executei o verificador e registrei a saída.','A origem permanece igual e a saída é determinística.']],
 ['Revisão: teste uma hipótese diferente','O aceite da amostra não cobre todo arquivo possível. Uma entrega honesta explicita o limite e testa algo além do exemplo. Um caso vazio ou uma coluna ausente revela suposições escondidas.','Peça testes adicionais para CSV vazio, data impossível e cabeçalho incompleto. Execute os testes e registre o que o programa suporta e o que falta.','Crie testes adicionais separados do verificador: entrada vazia, data impossível e cabeçalho incompleto. Revise tratamento de erros e explique as limitações. Não declare suporte sem executar.',['Testei pelo menos um caso adicional.','Registrei limitações observadas.']],
 ['Entrega: outra pessoa consegue usar?','A documentação deve ligar o objetivo à versão do código e aos comandos. Recriar em pasta nova testa dependências esquecidas. O resultado é um pequeno produto de dados, não uma conversa com a IA.','Preencha ENTREGA.md com resultado, decisões, comandos, limites e reversão. Copie a solução para uma pasta nova com o kit e rode verificar.py. Faça commit no seu repositório de estudo se usar Git.','Revise README.md e ENTREGA.md para outra pessoa reproduzir. Liste dependências, comando, saída esperada, limitações e como retornar à versão anterior. Preserve evidências reais.',['A reprodução em pasta nova foi conferida.','ENTREGA.md documenta resultado e limitações.']],
 ['Dossiê: conclua e escolha o próximo nó','Agora você tem objetivo, contrato, baseline, código, validação e documentação. Esta amostra completa permite experimentar o método antes da assinatura. O registro é autodeclarado; não é certificação nem correção automática por IA.','Exporte o dossiê e guarde junto da sua solução. Para continuar em projetos avançados de produto, agentes e MCPs com progresso por conta, escolha um plano da Academy.','Faça uma revisão final de CONTRATO.md, código, testes e ENTREGA.md. Compare com o objetivo inicial. Informe o que foi entregue, validado e ficou pendente.',['Guardei código, testes e dossiê.','Sei explicar a entrega sem depender da resposta da IA.']]
];

// A primeira experiência é uma atividade no navegador, sem editor ou instalação.
const salesText=`Vendas fictícias (não use dados de clientes):
1. V001 | 01/09/2026 | 2 unidades | R$ 25,00 por unidade
2. V002 | 02/09/2026 | 1 unidade | R$ 39,50 por unidade
3. V001 | 03/09/2026 | 1 unidade | R$ 25,00 por unidade
4. V003 | 30/02/2026 | 1 unidade | R$ 10,00 por unidade
5. V004 | 04/09/2026 | -1 unidade | R$ 10,00 por unidade
6. V005 | 05/09/2026 | 4 unidades | R$ 10,00 por unidade`;
const guidedStages=[
 {title:'Conheça sua missão',why:'Imagine que você precisa contar a uma pessoa quanto uma loja vendeu. A lista tem erros. Você vai usar a IA para organizar as vendas e depois conferir a resposta antes de entregar um relatório.',actions:['Abra um chat de IA que você já usa, em outra aba. Mantenha esta página aberta para seguir as orientações.','Se é sua primeira vez, um chat é a tela em que você escreve uma mensagem e recebe uma resposta da IA. A conta e os limites de uso são do serviço que você escolher.','Leia a missão: descobrir o total correto, explicar quais vendas ficaram de fora e entregar um texto que outra pessoa entenda.'],prompt:'Sou iniciante e nunca programei. Quero aprender a conferir uma lista de vendas fictícias com sua ajuda e preparar um relatório simples. Explique em linguagem comum como vamos trabalhar: eu faço o pedido, você responde e eu confiro. Não peça instalações nem código. Aguarde a lista de vendas.',checks:['Entendi que vou entregar um relatório de vendas.','Abri meu chat de IA e sei onde escrever uma mensagem.'],example:'Exemplo de anotação: vou conferir as vendas de uma loja fictícia e explicar o resultado para alguém que não viu a lista.',help:'Não tenho uma ferramenta de IA: escolha um chat a que você tenha acesso. A atividade não depende de uma marca específica. Se não puder usá-lo agora, leia o exemplo e retome quando tiver acesso.'},
 {title:'Conheça as vendas',why:'Leia a lista abaixo como se fosse uma planilha. “Unidades” é a quantidade vendida; “preço por unidade” é o valor de cada item. O valor de uma venda é quantidade × preço.',actions:['Veja as seis vendas abaixo. Todas são inventadas para esta atividade.','Procure três problemas: um número de venda repetido, uma data que não existe e uma quantidade negativa.','Mantenha apenas a primeira venda válida de cada número. Um número repetido não é uma nova venda.'],prompt:'Explique as colunas desta lista em linguagem simples e aponte registros que precisam de atenção. Não trate número repetido como nova venda; rejeite data impossível e quantidade negativa. Ainda não faça o relatório final.\n\n'+salesText,checks:['Entendi o que significam quantidade e preço.','Localizei a repetição, a data impossível e a quantidade negativa.'],example:'Exemplo: duas unidades a R$ 25,00 representam uma venda de R$ 50,00.',help:'Não entendi uma palavra: copie a mensagem desta etapa e peça à IA: “Explique como se eu estivesse vendo uma planilha pela primeira vez”.'},
 {title:'Faça o pedido à IA',why:'A IA precisa saber o que você quer e quais regras deve seguir. A mensagem abaixo já reúne a lista e as orientações. Você pode copiar, colar no seu chat e enviar.',actions:['Clique em “Copiar mensagem para a IA”. Volte ao seu chat, cole a mensagem no espaço de conversa e envie.','Espere a resposta. Ela deve separar as vendas que entram na conta das que ficam de fora e mostrar o cálculo.','Se a resposta vier com palavras difíceis, peça: “Explique sem termos de programação e mostre a conta em reais”.'],prompt:'Organize estas vendas fictícias e calcule o total em reais. Considere apenas a primeira ocorrência válida de cada número de venda. Exclua número repetido, data impossível e quantidade negativa. Mostre: vendas incluídas e seus valores, vendas excluídas com motivo, total em reais e quantas entraram e ficaram de fora. Use linguagem simples. Não invente registros nem gere código.\n\n'+salesText,checks:['Enviei a mensagem com a lista ao meu chat de IA.','Recebi o cálculo e os motivos das exclusões.'],example:'Exemplo de anotação: pedi para a IA separar as vendas válidas e mostrar como chegou ao total.',help:'A IA não lembra a lista: copie novamente a mensagem completa desta etapa. Se sua ferramenta limitar o uso, você pode pausar e voltar; o progresso fica neste navegador.'},
 {title:'Confira a resposta',why:'A resposta da IA pode parecer convincente e conter um erro. Compare a resposta com a lista original. Na conferência abaixo, informe o total e as quantidades que ela apresentou.',actions:['Confira se a venda repetida V001 ficou de fora e se a primeira V001 continuou na conta.','Confira se 30 de fevereiro e a quantidade -1 foram excluídos.','Preencha os três campos e clique em “Conferir os números”. Se houver diferença, peça à IA para revisar a conta com as regras.'],prompt:'Revise sua resposta usando a lista original. Confira o número V001 repetido, a data 30/02/2026 e a quantidade -1. Refaça a soma das vendas válidas e mostre cada parcela. Não inclua os registros rejeitados no total.',checks:['Comparei os motivos das exclusões com a lista.','Conferi os números pelo exemplo da atividade.'],example:'Exemplo de anotação: comparei cada venda com a resposta e conferi a soma; não aceitei apenas “está certo”.',help:'Os números não batem: abra “Veja a conta explicada”, identifique a diferença e leve essa diferença à IA. A conferência desta página é um gabarito fixo da atividade, não uma avaliação automática da conversa.'},
 {title:'Faça uma segunda conferência',why:'Uma conta certa para uma lista pode estar errada quando a situação muda. Faça uma pergunta pequena para ver se você e a IA entenderam a regra.',actions:['Na mesma conversa, pergunte o que mudaria se uma nova venda válida, com número diferente, de R$ 10,00 fosse adicionada.','A resposta deve aumentar o total em R$ 10,00: R$ 139,50. As três vendas excluídas continuam fora.','Se a resposta mudar as exclusões ou aumentar outro valor, peça uma revisão e anote o que aconteceu.'],prompt:'Sem alterar a lista original, imagine uma venda adicional válida, V006, em 06/09/2026: 1 unidade a R$ 10,00. Quanto seria o novo total? Mostre a soma, mantenha os três registros inválidos excluídos e explique a diferença em relação ao total original.',checks:['Perguntei sobre a venda adicional de R$ 10,00.','Comparei a resposta com R$ 139,50 e registrei o resultado.'],example:'Exemplo de anotação: a nova venda aumentou o total de R$ 129,50 para R$ 139,50; o relatório final continua usando a lista original.',help:'A IA misturou o exemplo com a lista original: diga “Esta era apenas uma hipótese. Volte às seis vendas originais para o relatório final”.'},
 {title:'Prepare seu relatório',why:'Agora transforme a conversa em algo que outra pessoa possa ler. Seu relatório deve dizer o total, explicar as exclusões e deixar claro que os dados são fictícios.',actions:['Copie a mensagem abaixo para pedir um rascunho à IA.','Leia o texto recebido. Confira R$ 129,50, três vendas incluídas e três excluídas. A venda extra da etapa anterior não deve entrar.','Cole o texto no campo “Meu relatório final”. Você pode editar as palavras para que ele fique claro para quem vai ler.'],prompt:'Prepare um relatório curto para alguém que não conhece programação, usando somente as seis vendas originais. Inclua: título, resumo do total em reais, três vendas incluídas, três vendas excluídas e seus motivos, e uma nota dizendo que os dados são fictícios e que a resposta foi conferida com a lista. Não inclua a venda adicional V006. Não afirme que você executou um programa. Use texto comum, sem código.',checks:['Li o relatório e conferi os números e as exclusões.','O texto explica que os dados são fictícios.'],example:'Exemplo de anotação: revisei o relatório para que alguém entenda o total e os motivos das exclusões sem abrir a conversa.',help:'O texto veio com código ou marcações difíceis: peça “Reescreva como um relatório curto em texto comum”. Não precisa de Word, planilha ou editor de código para concluir aqui.'},
 {title:'Explique com suas palavras',why:'Você deve conseguir explicar o que entregou sem depender da resposta da IA. Essa é a diferença entre copiar uma resposta e usar a IA com entendimento.',actions:['Escreva em sua anotação: qual era a tarefa, qual foi o resultado e por que três vendas ficaram de fora.','Diga também o limite: esta atividade usa seis vendas fictícias; não comprova que um sistema de vendas real foi verificado.','Se alguma parte ainda estiver confusa, volte à etapa correspondente e peça uma explicação mais simples.'],prompt:'Faça três perguntas simples para eu explicar meu relatório: qual era o objetivo, como conferi o resultado e quais são os limites da atividade. Espere minhas respostas. Não responda por mim e não diga que estou certificado.',checks:['Expliquei o resultado com minhas palavras.','Sei dizer o que foi conferido e o que não foi.'],example:'Exemplo: o total é R$ 129,50; excluí uma repetição, uma data impossível e uma quantidade negativa. Conferi apenas esta lista fictícia.',help:'Não consigo explicar ainda: volte à lista e à conta explicada. Você pode revisar quantas vezes precisar; não há cronômetro nem nota.'},
 {title:'Guarde sua entrega',why:'Sua entrega é o relatório que você revisou. O registro da atividade reúne suas anotações e os passos concluídos, para você lembrar como trabalhou.',actions:['Clique em “Baixar meu relatório” para guardar o texto que você revisou.','Clique em “Baixar meu registro” para guardar suas anotações. Os arquivos de texto podem ser abertos em um aplicativo comum de leitura de texto.','Para continuar estudando na Academy, escolha uma assinatura. Os projetos avançados incluem preparação de ferramentas e programação assistida por IA.'],prompt:'Revise meu relatório final em linguagem simples. Aponte se faltam o objetivo, o total das vendas originais, os motivos das exclusões ou a indicação de dados fictícios. Diferencie o que eu conferi do que não foi testado. Não invente validações.',checks:['Guardei meu relatório e entendi como foi produzido.','Sei o que vou praticar ao continuar na Academy.'],example:'Exemplo de anotação: guardei o relatório e o registro; sei explicar a conta e posso repetir a atividade com outra lista fictícia.',help:'Ainda não quero assinar: você pode concluir, baixar e guardar toda esta amostra gratuitamente. Os projetos seguintes ficam disponíveis com assinatura.'}
];
const sales=[['V001','01/09/2026','2','R$ 25,00'],['V002','02/09/2026','1','R$ 39,50'],['V001','03/09/2026','1','R$ 25,00'],['V003','30/02/2026','1','R$ 10,00'],['V004','04/09/2026','-1','R$ 10,00'],['V005','05/09/2026','4','R$ 10,00']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({stage:0,evidence:{},completed:[],statuses:{},attempts:{},checks:{}});
const clean=raw=>{const value=blank();if(!raw||typeof raw!=='object')return value;value.stage=Number.isInteger(raw.stage)&&raw.stage>=0&&raw.stage<8?raw.stage:0;value.completed=Array.isArray(raw.completed)?[...new Set(raw.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<8))]:[];value.evidence=Object.fromEntries(Object.entries(raw.evidence||{}).filter(([k,v])=>/^[0-7]$/.test(k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,5000)]));value.statuses=Object.fromEntries(Object.entries(raw.statuses||{}).filter(([k,v])=>/^[0-7]$/.test(k)&&Object.hasOwn(stateLabels,v)));for(const i of value.completed)value.statuses[i]='success';value.attempts=Object.fromEntries(Object.entries(raw.attempts||{}).filter(([k,v])=>/^[0-7]$/.test(k)&&Number.isInteger(v)&&v>=0));value.checks=raw.checks&&typeof raw.checks==='object'?raw.checks:{};return value;};
const key='datano-free-delivery-v2';const tools=['Meu chat de IA','Codex','Claude','Outra ferramenta'];
let state={mode:'guided',tracks:{guided:blank(),technical:blank()},report:'',numbers:{total:'',accepted:'',rejected:''},checked:false,tool:'Meu chat de IA'};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&typeof saved==='object'){state.mode=saved.mode==='technical'?'technical':'guided';state.tracks={guided:clean(saved.tracks?.guided),technical:clean(saved.tracks?.technical)};state.report=typeof saved.report==='string'?saved.report.slice(0,15000):'';state.tool=tools.includes(saved.tool)?saved.tool:'Meu chat de IA';if(saved.numbers&&typeof saved.numbers==='object')for(const k of ['total','accepted','rejected'])state.numbers[k]=String(saved.numbers[k]??'').slice(0,20);state.checked=saved.checked===true&&validNumbers(state.numbers);}else{const legacy=JSON.parse(localStorage.getItem('datano-free-delivery-v1'));if(legacy)state.tracks.technical=clean(legacy);}}catch{}
const target=document.querySelector('#free-delivery');
const track=()=>state.tracks[state.mode];
const stages=()=>state.mode==='guided'?guidedStages:technicalStages.map(s=>({title:s[0],why:s[1],actions:[s[2]],prompt:s[3],checks:s[4]}));
function save(){try{localStorage.setItem(key,JSON.stringify(state));cloud?.changed();return true;}catch{return false;}}
function validNumbers(n){const amount=String(n.total).replace(/^\s*R\$\s*/,'').trim();if(!/^\d+(?:[,.]\d{1,2})?$/.test(amount))return false;return Math.round(Number(amount.replace(',','.'))*100)===12950&&String(n.accepted).trim()==='3'&&String(n.rejected).trim()==='3';}
function feedback(message){target.querySelector('#delivery-feedback').textContent=message;}
function invalidate(from){const t=track();t.completed=t.completed.filter(i=>i<from);for(let i=from;i<8;i++)t.statuses[i]=i===from?'in_progress':'pending';}
function failed(message){const t=track();t.statuses[t.stage]='failed';t.attempts[t.stage]=(Number(t.attempts[t.stage])||0)+1;save();render();feedback(message);}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function salesTable(){return `<div class="delivery-table-wrap" role="region" aria-label="Lista de vendas; deslize ou use as setas para ver todas as colunas" tabindex="0"><table><caption>As seis vendas da loja fictícia</caption><thead><tr><th scope="col">Venda</th><th scope="col">Data</th><th scope="col">Unidades</th><th scope="col">Preço por unidade</th></tr></thead><tbody>${sales.map(row=>`<tr>${row.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function render(){if(!target)return;const current=track(),s=stages()[current.stage],guided=state.mode==='guided';target.innerHTML=`
 <div class="section-heading"><div><span class="eyebrow">AMOSTRA COMPLETA · SEM CADASTRO</span><h2>Sua primeira entrega com IA, passo a passo.</h2></div></div>
 <p><a class="button ghost" href="#agents-sample">Quero uma entrega completa com Datano-Agents ↑</a></p><p class="delivery-intro">Nunca programou? Comece por uma tarefa simples: organizar vendas fictícias e entregar um relatório claro. Você vai pedir ajuda à IA, conferir a resposta e guardar o resultado.</p>
 <details class="delivery-welcome"><summary>O que preparar · como funciona</summary><p>Um navegador e acesso a um chat de IA de sua escolha, aberto em outra aba. Na atividade sem programação, você não precisa instalar nada, abrir um terminal ou escrever código. Reserve cerca de 20–30 minutos; pode pausar e voltar.</p><p><strong>Como funciona:</strong> esta página orienta. Você copia uma mensagem, envia ao seu chat de IA e volta para conferir a resposta. Sua ferramenta de IA tem conta e limites próprios; a atividade na Academy é gratuita.</p></details>
 <div class="delivery-actions"><label>Como quero praticar<select id="delivery-mode"><option value="guided" ${guided?'selected':''}>Sem programação · começar do zero</option><option value="technical" ${!guided?'selected':''}>Com código · prática opcional</option></select></label><label>Onde vou conversar com a IA<select id="delivery-tool">${tools.map(t=>`<option ${state.tool===t?'selected':''}>${t}</option>`).join('')}</select></label>${!guided?'<a class="button primary" href="starter-kit.zip" download>Baixar kit de prática ↓</a>':''}</div>
 ${!guided?'<p>Esta opção exige Python 3.10+ e um editor, além da sua ferramenta de IA. Reserve 60–90 minutos. Se esses nomes são novos para você, escolha “Sem programação” primeiro.</p>':''}
 ${stepProgress({titles:stages().map(s=>s.title),current:current.stage,statuses:current.statuses})}
 <div class="delivery-layout"><nav aria-label="Etapas da amostra">${stages().map((x,i)=>`<button data-delivery-stage="${i}" aria-current="${i===current.stage?'step':'false'}"><span>${current.completed.includes(i)?'✓':current.statuses[i]==='failed'?'!':String(i+1).padStart(2,'0')}</span>${esc(x.title)}<small>${stateLabels[current.statuses[i]||'pending']}</small></button>`).join('')}</nav>
 <section class="delivery-stage learning-step-enter" aria-labelledby="delivery-stage-title"><span class="eyebrow">PASSO ${current.stage+1} DE 8</span><h3 id="delivery-stage-title" tabindex="-1">${esc(s.title)}</h3><span class="learning-state" data-state="${current.statuses[current.stage]||'pending'}">${stateLabels[current.statuses[current.stage]||'pending']}</span>${current.stage?'<button type="button" class="button ghost learning-prev" id="delivery-prev">← Etapa anterior</button>':''}<p class="learning-save">Seu rascunho é salvo enquanto você escreve.</p><p>${esc(s.why)}</p><h4>O que fazer agora</h4><ol class="delivery-instructions">${s.actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ol>
 ${guided&&current.stage>=1&&current.stage<=4?salesTable():''}
 <details><summary>${guided?'Veja a mensagem pronta para enviar':'Veja o pedido para sua ferramenta de IA'}</summary><pre id="delivery-prompt" tabindex="-1">${esc(s.prompt)}</pre></details><button class="button ghost" id="delivery-copy">Copiar mensagem para a IA →</button><p class="delivery-tip">Depois de copiar, cole a mensagem no seu chat e envie. A resposta aparece lá; volte aqui para seguir a atividade.</p>
 ${guided&&current.stage===3?`<form id="delivery-numbers" class="delivery-number-check"><h4>Compare os números da resposta</h4><label>Total em reais<input name="total" inputmode="decimal" value="${esc(state.numbers.total)}" placeholder="Ex.: 50,00" required></label><label>Quantas vendas entraram na conta?<input name="accepted" inputmode="numeric" value="${esc(state.numbers.accepted)}" required></label><label>Quantas vendas ficaram de fora?<input name="rejected" inputmode="numeric" value="${esc(state.numbers.rejected)}" required></label><button class="button ghost">Conferir os números</button><p id="delivery-number-result" role="status">${state.checked?'Números conferidos: R$ 129,50, três vendas incluídas e três excluídas.':''}</p></form><details><summary>Veja a conta explicada</summary><p>V001: 2 × R$ 25,00 = R$ 50,00. V002: 1 × R$ 39,50 = R$ 39,50. V005: 4 × R$ 10,00 = R$ 40,00. Total: <strong>R$ 129,50</strong>. As outras três vendas foram excluídas: V001 repetida, V003 com 30 de fevereiro e V004 com quantidade negativa.</p></details>`:''}
 ${guided&&current.stage===5?`<label class="delivery-report-label">Meu relatório final<textarea id="delivery-report" rows="10" maxlength="15000" placeholder="Cole o relatório da IA e revise o texto. Inclua o total, as vendas excluídas e a indicação de dados fictícios.">${esc(state.report)}</textarea></label><p>Seu texto fica neste navegador. Você poderá baixá-lo na conclusão.</p>`:''}
 ${s.help?`<details class="delivery-help"><summary>Preciso de ajuda nesta etapa</summary><p>${esc(s.help)}</p></details>`:''}
 <details class="journey-support"><summary>Praticar em uma tela simulada</summary><datano-simulation scenario="${guided?(current.stage<3?'brief':'review'):'terminal'}"></datano-simulation></details><form id="delivery-evidence" novalidate><label>${guided?'Minha anotação desta etapa':'Evidência da sua execução'}<textarea name="evidence" rows="3" maxlength="5000" placeholder="${guided?esc(s.example):'Registre o que fez e o resultado observado.'}">${esc(current.evidence[current.stage]||'')}</textarea></label><p class="delivery-tip">Escreva uma frase sobre o que fez ou entendeu. Não inclua senhas nem dados pessoais.</p><fieldset><legend>Posso seguir quando…</legend>${s.checks.map((c,i)=>`<label class="delivery-check"><input type="checkbox" data-delivery-check="${i}" ${current.completed.includes(current.stage)||current.checks[current.stage]?.[i]?'checked':''}>${esc(c)}</label>`).join('')}</fieldset><button class="button primary">Salvar etapa e continuar →</button></form><p id="delivery-feedback" class="learning-result" role="status"></p></section></div>
 <details class="delivery-finish" ${current.stage===7?'open':''}><summary>Guardar minha entrega · próximos passos</summary><div><div><h3>${current.completed.length===8?'Você concluiu a atividade. Guarde sua entrega.':'Sua entrega fica com você.'}</h3><p>${guided?'O relatório contém o texto que você revisou. O registro reúne suas anotações. Você pode baixar ambos sem assinar.':'Guarde as anotações junto do código e dos testes da sua prática.'}</p>${guided?'<button class="button ghost" id="delivery-report-export">Baixar meu relatório ↓</button> ':''}<button class="button ghost" id="delivery-export">Baixar meu registro ↓</button></div><div><p>Quer continuar? A assinatura libera os projetos seguintes, as aulas e o progresso salvo na sua conta.</p><a class="button primary" href="https://academy.datano.com.br/#planos">Continuar na Academy · Assinar ↗</a></div></div></details>
 <details class="journey-support"><summary>Como os textos e o progresso são guardados</summary><p class="public-note">Sem conectar a conta, seu progresso e seus textos ficam neste navegador. Ao escolher salvar na conta gratuita, as etapas e os textos são enviados à Academy para retomada em outros dispositivos. A Academy não lê a conversa no seu chat, nem corrige automaticamente seu relatório. A conferência dos números usa o exemplo desta atividade. Ao concluir, salve na conta gratuita para emitir o certificado de jornada simplificada. Baixe seus arquivos antes de limpar os dados do navegador.</p></details>`;}
function advanceFocus(){target.querySelector('#delivery-stage-title').focus({preventScroll:true});target.querySelector('.delivery-stage').scrollIntoView({block:'start'});}
if(target){render();cloud=connectJourney({root:target,getId:()=>'foundation',getState:()=>state,applyState:value=>{state={...state,...value,tracks:{guided:clean(value.tracks?.guided),technical:clean(value.tracks?.technical)}};save();render();advanceFocus();},isReady:()=>state.tracks.guided.completed.length===8&&state.checked&&state.report.trim().length>=80});target.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='delivery-prev'){track().stage=Math.max(0,track().stage-1);save();render();advanceFocus();}if(b.dataset.deliveryStage!==undefined){track().stage=Number(b.dataset.deliveryStage);save();render();advanceFocus();}if(b.id==='delivery-copy'){await copyText(stages()[track().stage].prompt,target.querySelector('#delivery-prompt'),target.querySelector('#delivery-feedback'));}if(b.id==='delivery-report-export'){if(state.report.trim().length<80){feedback('Prepare seu relatório no passo 6 antes de baixar.');return;}download('Relatório de vendas fictícias — Datano\n\n'+state.report+'\n\nTexto revisado pelo aluno com apoio de IA. Atividade com dados fictícios.\n','meu-relatorio-datano.txt');}if(b.id==='delivery-export'){const current=track();const text=['Minha primeira entrega com IA — Datano',`Atividade: ${state.mode==='guided'?'Sem programação':'Com código'}`,`Data: ${new Date().toLocaleDateString('pt-BR')}`,'Este registro reúne as anotações do aluno; não é uma certificação.'].concat(stages().map((s,i)=>`${i+1}. ${s.title}\nEstado: ${current.completed.includes(i)?'Concluído pelo aluno':'Pendente'}\nAnotação: ${current.evidence[i]||'Não registrada.'}`)).join('\n\n');download(text,'minha-jornada-datano.txt');}});
 target.addEventListener('input',e=>{if(e.target.id==='delivery-report'){invalidate(5);state.report=e.target.value;save();}if(e.target.name==='evidence'){invalidate(track().stage);track().evidence[track().stage]=e.target.value;save();}if(e.target.form?.id==='delivery-numbers'){invalidate(3);state.numbers[e.target.name]=e.target.value;state.checked=false;save();target.querySelector('#delivery-number-result').textContent='Confira novamente depois de alterar os números.';}});
 target.addEventListener('change',e=>{if(e.target.dataset.deliveryCheck!==undefined){const t=track();t.checks[t.stage]=Array.from(target.querySelectorAll('[data-delivery-check]')).map(b=>b.checked);save();}if(e.target.id==='delivery-mode'){state.mode=e.target.value==='technical'?'technical':'guided';save();render();}if(e.target.id==='delivery-tool'){state.tool=e.target.value;save();render();}});
 target.addEventListener('submit',e=>{if(e.target.id==='delivery-numbers'){e.preventDefault();state.numbers=Object.fromEntries(new FormData(e.target));state.checked=validNumbers(state.numbers);track().statuses[3]=state.checked?'in_progress':'failed';if(!state.checked)track().attempts[3]=(Number(track().attempts[3])||0)+1;save();target.querySelector('#delivery-number-result').textContent=state.checked?'Números conferidos: R$ 129,50, três vendas incluídas e três excluídas.':'Há uma diferença. Compare as exclusões e abra “Veja a conta explicada”. Peça à IA para revisar antes de continuar.';return;}if(e.target.id!=='delivery-evidence')return;e.preventDefault();const current=track();if(state.mode==='guided'&&current.stage===3&&!state.checked){failed('Confira os três números no formulário desta etapa antes de continuar.');return;}if(state.mode==='guided'&&[5,7].includes(current.stage)&&state.report.trim().length<80){failed('Prepare um relatório com pelo menos 80 caracteres no passo 6 antes de continuar.');return;}const evidence=String(new FormData(e.target).get('evidence')).trim();if(evidence.length<20){failed('Escreva uma frase com pelo menos 20 caracteres contando o que fez ou entendeu.');return;}if(Array.from(e.target.querySelectorAll('input[type=checkbox]')).some(b=>!b.checked)){failed('Confira os dois itens de aceite antes de seguir. Seu texto foi preservado.');return;}current.statuses[current.stage]='success';current.evidence[current.stage]=evidence;current.completed=[...new Set([...current.completed,current.stage])];current.stage=Math.min(current.stage+1,7);const stored=save();render();feedback(stored?'Etapa salva. Siga o próximo passo no seu ritmo.':'Não foi possível guardar no navegador. Baixe seu registro para preservar as anotações.');advanceFocus();});
}
