// Currículo introdutório público, autoral e independente dos arquivos da Academy.
const academy='https://academy.datano.com.br';
const sources={codex:['Codex CLI','https://learn.chatgpt.com/docs/codex/cli'],ide:['Codex no editor','https://learn.chatgpt.com/docs/codex/ide'],commands:['Comandos Codex','https://learn.chatgpt.com/docs/developer-commands'],docs:['MCP de documentação OpenAI','https://developers.openai.com/learn/docs-mcp'],claude:['Primeiros passos Claude Code','https://code.claude.com/docs/en/quickstart'],mcp:['MCP no Claude Code','https://code.claude.com/docs/en/mcp']};
const journeys={
 codex:{name:'Codex',next:'Da primeira tarefa à revisão de código, instruções de projeto e automações com Codex.',lessons:[
 {title:'Abra seu primeiro espaço de prática',minutes:5,text:'Comece em uma pasta de estudo, usando um arquivo sem dados pessoais. Instale o Codex pelo guia oficial e autentique pelo fluxo de login. Na CLI, você conversa pelo terminal. No VS Code, a extensão permite trabalhar com os arquivos do editor.',command:'codex --version\ncodex login\ncodex',label:'No terminal, depois de instalar o Codex',extra:'Alternativa no VS Code: procure a extensão oficial OpenAI Codex na loja do editor e siga o login. Os requisitos e a disponibilidade dependem da sua conta.',exercise:'Abra a ferramenta e localize a pasta que será usada no exercício. Confira qual conta e ambiente estão ativos antes de pedir uma alteração.',refs:['codex','ide']},
 {title:'Faça um pedido pequeno e confira o resultado',minutes:7,text:'Um bom primeiro pedido diz o objetivo, o arquivo e como você vai conferir o resultado. Use uma página de apresentação fictícia para praticar. Comece pedindo uma explicação; depois solicite uma mudança pequena e examine o arquivo.',command:'Leia o arquivo index.html e explique o que ele faz.\nDepois proponha um título mais claro. Aguarde minha confirmação antes de editar.',label:'Prompt para enviar na conversa do Codex',extra:'Se sua pasta ainda estiver vazia, peça primeiro: “Crie uma página HTML simples sobre um projeto fictício”. Na conversa da CLI, /status ajuda a consultar o estado da sessão. No terminal, codex --help mostra as opções disponíveis.',exercise:'Compare a explicação com o arquivo. Depois de autorizar a mudança, abra a página no navegador e confira o novo título.',refs:['commands']},
 {title:'Conecte seu primeiro MCP de documentação',minutes:6,text:'MCP conecta o assistente a ferramentas externas. Para começar, experimente uma fonte pública de documentação: você aprende a registrar uma conexão e pedir uma consulta, sem usar bases corporativas. Registrar o servidor é uma etapa; consultar a documentação é outra.',command:'codex mcp add openaiDeveloperDocs --url https://developers.openai.com/mcp\ncodex mcp list',label:'No terminal, fora da conversa do Codex',extra:'Abra uma nova sessão e peça: “Consulte a documentação oficial pelo MCP e explique como começar com Codex no editor. Inclua o link da fonte”. A configuração MCP é compartilhada entre CLI e extensão do mesmo host Codex.',exercise:'Confira o servidor na lista, faça a consulta e abra a fonte para comparar a resposta. Conheça também os projetos públicos Excel MCP e Windows MCP na seção abaixo.',refs:['docs']}
 ]},
 claude:{name:'Claude',next:'Continue com Claude Desktop, Claude Code, VS Code, instruções de projeto e fluxos com MCPs.',lessons:[
 {title:'Escolha a superfície e abra Claude Code',minutes:5,text:'Claude Desktop é o aplicativo para conversas e seus próprios fluxos. Claude Code é a ferramenta de desenvolvimento disponível no terminal e no editor. Nesta jornada, use Claude Code em uma pasta de estudo. Instale pelo guia oficial, inicie a ferramenta e siga a autenticação.',command:'claude --version\nclaude',label:'No terminal, depois de instalar Claude Code',extra:'No Windows, o guia oficial também oferece winget install Anthropic.ClaudeCode. Confira os requisitos para seu sistema. Se preferir o editor, instale a extensão oficial Claude Code da Anthropic no VS Code. Uma conta e acesso compatível com a ferramenta são necessários.',exercise:'Abra uma pasta de exercício e entre no Claude Code. Identifique o que está aberto: terminal, extensão ou aplicativo Desktop.',refs:['claude']},
 {title:'Peça uma explicação antes de editar',minutes:7,text:'Dê uma tarefa que você consiga avaliar. Use um README curto de um projeto fictício e peça ao Claude para explicar seu conteúdo. Depois, solicite uma melhoria por vez. O objetivo é aprender a conversar com contexto e verificar a entrega.',command:'Leia o README.md e resuma o objetivo em três frases.\nSugira uma melhoria na introdução, sem alterar o arquivo ainda.',label:'Prompt para enviar na conversa do Claude Code',extra:'Com a ferramenta aberta, /help mostra os comandos da sessão. No terminal, claude --help mostra as opções da CLI. Depois de autorizar a edição, confira a alteração no próprio arquivo ou no diff do editor.',exercise:'Escreva o README fictício, compare o resumo com o original e autorize uma melhoria. Verifique se o texto preservou o objetivo do projeto.',refs:['claude']},
 {title:'Use um MCP público para consultar uma fonte',minutes:6,text:'Claude Code também pode conectar servidores MCP. Vamos usar o mesmo servidor público de documentação OpenAI para comparar as duas ferramentas. Esse exemplo é para Claude Code; configurações do aplicativo Claude Desktop são tratadas separadamente.',command:'claude mcp add --transport http openaiDeveloperDocs https://developers.openai.com/mcp\nclaude mcp list',label:'No terminal, dentro da pasta de estudo',extra:'Abra uma nova sessão do Claude Code e use /mcp para conferir as conexões. Peça: “Consulte a documentação OpenAI pelo MCP e localize os primeiros passos do Codex CLI. Inclua a fonte”. Para outras ferramentas, examine a origem, as permissões e os requisitos antes de conectá-las.',exercise:'Confira a conexão e compare a resposta com a página oficial. Explore os READMEs públicos dos MCPs Excel e Windows antes de pensar em automações.',refs:['mcp','docs']}
 ]}
};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='codex',progress={codex:[],claude:[]};
try{const saved=JSON.parse(localStorage.getItem('datano-public-journeys-v1'));for(const key of Object.keys(progress))if(Array.isArray(saved?.[key]))progress[key]=saved[key].filter(i=>Number.isInteger(i)&&i>=0&&i<3);}catch{}
const section=document.createElement('section');section.className='public-section journeys';section.id='jornadas';
section.innerHTML=`<div class="section-heading"><div><span class="eyebrow">COMECE AQUI · GRATUITO</span><h2>Seu primeiro passo com IA.</h2></div><span>2 jornadas · 6 aulas curtas</span></div><p>Aprenda o básico, experimente no seu ambiente e continue a trilha completa na DatanO Academy. Estas aulas são gratuitas, sem cadastro. O uso de Codex e Claude segue os planos e requisitos de cada fornecedor.</p><div class="journey-choices" role="group" aria-label="Escolha sua jornada"><button class="button primary" data-journey="codex" aria-pressed="true">Começar com Codex</button><button class="button ghost" data-journey="claude" aria-pressed="false">Começar com Claude</button></div><div id="journey-content"></div><p class="public-note">O progresso é autodeclarado e salvo neste navegador. Os comandos são exemplos para executar no seu ambiente; esta página não executa agentes nem MCPs. Fontes revisadas em 2 de outubro de 2026.</p>`;
document.querySelector('#destinos').after(section);
function render(){const j=journeys[selected],done=progress[selected];document.querySelector('#journey-content').innerHTML=`<div class="journey-progress"><span id="journey-progress-label">${j.name} · ${done.length} de 3 aulas praticadas</span><progress max="3" value="${done.length}" aria-labelledby="journey-progress-label"></progress></div>${j.lessons.map((l,i)=>`<details class="starter-lesson" ${i===0?'open':''}><summary><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><span>${l.title}<small>${l.minutes} min · ${done.includes(i)?'Praticada ✓':'Introdução'}</small></span></summary><div class="starter-body"><p>${l.text}</p><span class="command-label">${l.label}</span><div class="starter-code"><pre><code>${escape(l.command)}</code></pre><button class="button ghost" data-copy="${i}" aria-label="Copiar exemplo da aula ${i+1}">Copiar</button></div><p>${l.extra}</p><div class="starter-exercise"><strong>Experimente agora</strong><p>${l.exercise}</p><label><input type="checkbox" data-practice="${i}" ${done.includes(i)?'checked':''}>Pratiquei e conferi o resultado</label></div><p class="starter-sources">Fontes oficiais: ${l.refs.map(id=>`<a href="${sources[id][1]}" target="_blank" rel="noopener">${sources[id][0]} ↗</a>`).join(' · ')}</p></div></details>`).join('')}<div class="journey-next"><div><span class="eyebrow">CONTINUE SUA JORNADA</span><h3>${done.length===3?'Primeiros passos concluídos. Vamos além?':'Do básico à prática completa.'}</h3><p>${j.next}</p><p class="public-note">No público: primeiros comandos, pedidos simples e MCP de documentação.<br>Na Academy paga: trilhas completas, laboratórios, revisão, automação e orquestrações.</p></div><a class="button primary" href="${academy}/#planos">Continuar com ${j.name} na Academy ↗</a></div><p id="journey-feedback" role="status"></p>`;}
section.addEventListener('click',async e=>{const tab=e.target.closest('[data-journey]');if(tab){selected=tab.dataset.journey;section.querySelectorAll('[data-journey]').forEach(b=>{const active=b===tab;b.setAttribute('aria-pressed',String(active));b.className='button '+(active?'primary':'ghost');});render();}const copy=e.target.closest('[data-copy]');if(copy){const text=journeys[selected].lessons[Number(copy.dataset.copy)].command;try{await navigator.clipboard.writeText(text);document.querySelector('#journey-feedback').textContent='Exemplo copiado. Use no ambiente indicado na aula.';}catch{document.querySelector('#journey-feedback').textContent='Selecione o exemplo e copie pelo seu navegador.';}}});
section.addEventListener('change',e=>{if(!e.target.matches('[data-practice]'))return;const i=Number(e.target.dataset.practice),checked=e.target.checked;progress[selected]=progress[selected].filter(n=>n!==i);if(checked)progress[selected].push(i);try{localStorage.setItem('datano-public-journeys-v1',JSON.stringify(progress));}catch{}const count=progress[selected].length;document.querySelector('#journey-progress-label').textContent=`${journeys[selected].name} · ${count} de 3 aulas praticadas`;section.querySelector('progress').value=count;e.target.closest('details').querySelector('summary small').textContent=journeys[selected].lessons[i].minutes+' min · '+(checked?'Praticada ✓':'Introdução');section.querySelector('.journey-next h3').textContent=count===3?'Primeiros passos concluídos. Vamos além?':'Do básico à prática completa.';document.querySelector('#journey-feedback').textContent=checked?'Prática registrada.':'Prática desmarcada.';});
render();
