import {esc} from './learning-ui.js';
const academy='https://academy.datano.com.br';
async function api(path,body,method=body?'POST':'GET'){
 const r=await fetch(path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let value;try{value=await r.json();}catch{throw Object.assign(Error('A conta está disponível na Academy.'),{status:r.status});}if(!r.ok)throw Object.assign(Error(value.error||'Não foi possível salvar agora.'),{status:r.status,current:value.current});return value;
}
export function connectJourney({root,getId,getState,applyState,isReady}){
 const box=document.createElement('aside');box.className='learning-cloud';box.setAttribute('aria-label','Conta e progresso da jornada');root.before(box);
 let user=null,enabled=false,revision=0,remote=null,loading=true,timer,busy=false,dirty=false,message='',generation=0,certificate=null;
 const id=()=>getId();
 function accountUrl(path){const course=id(),next=course==='foundation'?'/comecar#free-delivery':'/comecar?missao='+encodeURIComponent(course.replace(/^agents-/,''))+'#agents-sample';const local=location.origin===academy||['localhost','127.0.0.1','[::1]'].includes(location.hostname);return (local?'':academy)+path+'?next='+encodeURIComponent(next);}
 function draw(){
  box.innerHTML=`<strong>${user?'Seu espaço, '+esc(user.name):'Seu próximo passo fica guardado.'}</strong><p>${esc(message||(loading?'Conferindo sua conta…':user?'Escolha o progresso que deseja usar nesta jornada.':'Pratique sem cadastro ou crie uma conta gratuita para continuar em outro dispositivo e emitir seu certificado.'))}</p>${user?`<div class="learning-toolbar">${!enabled?`<button class="button ghost" type="button" data-cloud-local>${remote?'Usar progresso deste navegador':'Salvar na minha conta'}</button>${remote?'<button class="button primary" type="button" data-cloud-resume>Retomar progresso da conta →</button>':''}`:'<button class="button ghost" type="button" data-cloud-save>Salvar progresso agora</button>'}${isReady()?'<button class="button primary" type="button" data-cloud-certificate>Emitir certificado de conclusão →</button>':''}${certificate?`<a class="button ghost" href="/certificado/${encodeURIComponent(certificate.token)}" target="_blank" rel="noopener">Abrir meu certificado ↗</a>`:''}<a href="/conta">Minha conta e certificados →</a></div>`:`<div class="learning-toolbar"><a class="button primary" href="${accountUrl('/cadastro')}">Criar conta gratuita →</a><a class="button ghost" href="${accountUrl('/entrar')}">Já tenho conta</a></div>`}<small>${enabled?'Sincronização ligada para esta conta.':'Seus rascunhos atuais permanecem neste navegador.'} Conta gratuita não exige cartão. O curso avançado exige assinatura.</small>`;
 }
 async function refresh(){const gen=++generation;enabled=false;remote=null;revision=0;certificate=null;message='';loading=true;draw();try{const me=await api('/api/me');if(gen!==generation)return;user=me.user;const data=await api('/api/learning/'+encodeURIComponent(id()));if(gen!==generation)return;remote=data.state;revision=data.revision;loading=false;message=remote?'Há progresso salvo na sua conta. Escolha retomar ou manter os textos deste navegador.':'Conecte esta jornada à sua conta para salvar as próximas etapas.';}catch(error){if(gen!==generation)return;loading=false;if(error.status===401||error.status===404){user=null;if(error.status===404)message='Sua conta fica na Academy. Abra a mesma missão por um dos botões abaixo; os rascunhos desta vitrine continuam neste navegador.';}else message='Não foi possível conferir sua conta. Seus textos locais continuam disponíveis. Recarregue para tentar novamente.';}draw();}
 async function flush(){if(!enabled||!user)return false;if(busy){dirty=true;return false;}busy=true;dirty=false;const gen=generation,course=id(),snapshot=structuredClone(getState());message='Salvando na sua conta…';draw();try{const data=await api('/api/learning/'+encodeURIComponent(course),{revision,state:snapshot},'PUT');if(gen!==generation)return false;revision=data.revision;remote=data.state;message='Progresso salvo na sua conta ✓';return true;}catch(error){if(gen!==generation)return false;if(error.status===409){enabled=false;remote=error.current?.state;revision=error.current?.revision??revision;message='O progresso mudou em outro dispositivo. Seus textos locais foram preservados. Escolha qual versão continuar.';}else if(error.status===401){enabled=false;user=null;message='Sua sessão terminou. Entre novamente; os textos deste navegador foram preservados.';}else message='Falha ao salvar na conta. Seus textos estão neste navegador. Use “Salvar progresso agora” para tentar novamente.';return false;}finally{busy=false;draw();if(dirty&&enabled){clearTimeout(timer);timer=setTimeout(flush,250);}}}
 box.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-cloud-local')){enabled=true;await flush();}if(b.hasAttribute('data-cloud-resume')){applyState(structuredClone(remote));enabled=true;message='Progresso da conta carregado. Continue da etapa em que parou.';draw();}if(b.hasAttribute('data-cloud-save'))await flush();if(b.hasAttribute('data-cloud-certificate')){const certGeneration=generation,certCourse=id();b.disabled=true;try{if(!enabled){message='Salve ou retome o progresso da conta antes de emitir o certificado.';draw();return;}if(busy){message='Aguarde o salvamento e tente emitir novamente.';draw();return;}if(!await flush()||certGeneration!==generation)return;const result=await api('/api/certificates',{course_id:certCourse});if(certGeneration!==generation)return;certificate=result.certificate;message='Certificado emitido ✓ Abra para baixar ou imprimir.';}catch(error){if(certGeneration!==generation)return;message=error.message;}draw();}});
 draw();void refresh();
 return {changed(){draw();if(enabled){dirty=true;clearTimeout(timer);timer=setTimeout(flush,650);}},refresh(){clearTimeout(timer);void refresh();}};
}
