// Componentes de prática. Nenhuma simulação executa código, modelo ou conexão.
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const stateLabels={pending:'Não iniciada',in_progress:'Em andamento',success:'Concluída',failed:'Precisa de ajuste'};
export function mountJourneySwitch(){
 const agents=document.querySelector('#agents-sample'),foundation=document.querySelector('#free-delivery');if(!agents||!foundation||document.querySelector('#journey-choice'))return;
 const nav=document.createElement('nav');nav.className='journey-choice';nav.setAttribute('aria-label','Escolha da jornada gratuita');nav.innerHTML='<label for="journey-choice">Jornada gratuita</label><select id="journey-choice"><option value="agents-sample">DatanO-Agents · minha entrega completa</option><option value="free-delivery">Fundamentos · relatório com IA</option></select>';(agents.previousElementSibling?.classList.contains('learning-cloud')?agents.previousElementSibling:agents).before(nav);
 const select=nav.querySelector('select');let chosen='agents-sample';try{if(localStorage.getItem('datano-free-journey')==='free-delivery')chosen='free-delivery';}catch{}
 function show(id,focus=false){chosen=id;select.value=id;for(const root of [agents,foundation]){root.hidden=root.id!==id;const cloud=root.previousElementSibling;if(cloud?.classList.contains('learning-cloud'))cloud.hidden=root.hidden;}try{localStorage.setItem('datano-free-journey',id);}catch{}if(focus){nav.scrollIntoView({block:'start'});document.querySelector('#'+id+' h2')?.setAttribute('tabindex','-1');document.querySelector('#'+id+' h2')?.focus({preventScroll:true});}}
 function route(){const id=location.hash.slice(1);if(['agents-sample','free-delivery'].includes(id))show(id);}
 const hash=location.hash.slice(1);show(['agents-sample','free-delivery'].includes(hash)?hash:chosen);select.addEventListener('change',()=>{history.replaceState(null,'',location.pathname+location.search+'#'+select.value);show(select.value,true);});window.addEventListener('hashchange',route);
}
export function stepProgress({titles,current,statuses={},action}){
 const count=titles.filter((_,i)=>statuses[i]==='success').length;
 return `<div class="learning-progress"><div><strong>${count} de ${titles.length} etapas concluídas</strong><span>${Math.round(count/titles.length*100)}%</span></div><progress max="${titles.length}" value="${count}" aria-label="Etapas concluídas"></progress>${action?`<nav class="learning-path" aria-label="Mapa da jornada">${titles.map((t,i)=>`<button type="button" data-${action}="${i}" data-state="${esc(statuses[i]||'pending')}" aria-current="${i===current?'step':'false'}"><span aria-hidden="true">${statuses[i]==='success'?'✓':statuses[i]==='failed'?'!':i+1}</span><strong>${esc(t)}</strong><small>${stateLabels[statuses[i]||'pending']}</small></button>`).join('')}</nav>`:''}</div>`;
}
export async function copyText(text,area,feedback){
 try{await navigator.clipboard.writeText(text);if(feedback)feedback.textContent='Copiado ✓ Cole na ferramenta indicada e volte para conferir.';return true;}
 catch{if(area){area.closest('details')?.setAttribute('open','');if('value' in area){area.value=text;area.focus();area.select();}else{const range=document.createRange();range.selectNodeContents(area);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);area.focus();}}if(feedback)feedback.textContent='Cópia automática indisponível. O texto está selecionado; use Copiar no seu aparelho.';return false;}
}
const scenarios={
 brief:{title:'Conversa com a IA',prompt:'Quero divulgar meu serviço. O que falta neste pedido?',bad:'Pedido incompleto',good:'Pedido com objetivo e limites',failed:['Você: “Faça uma divulgação.”','IA: “Qual serviço? Para quem? Posso prometer desconto?”','Falha: faltam objetivo, público e condições confirmadas.'],passed:['Você: “Apresente consertos de roupas ao bairro. Peças serão avaliadas; não invente preços ou prazos.”','IA: “Vou preparar uma apresentação clara com essas condições.”','Concluído: o pedido define resultado, público e limites.'],fix:'Diga o resultado, quem vai usar e quais informações já foram confirmadas.'},
 review:{title:'Mesa de revisão',prompt:'Confira um rascunho antes de entregar.',bad:'Texto com promessa sem confirmação',good:'Texto revisado',failed:['Rascunho: “Entrega em 24 horas, preço garantido.”','Revisor: “Essas condições não estão no objetivo.”','Falha: uma promessa inventada impede a aprovação.'],passed:['Rascunho: “Cada pedido será avaliado antes de combinar condições.”','Revisor: “Condições preservadas e texto claro.”','Concluído: o texto pode seguir para a conferência humana.'],fix:'Retire a promessa e registre o que precisa de confirmação. Depois faça uma nova revisão.'},
 terminal:{title:'Tela de execução',prompt:'Observe como um teste revela uma falha e como conferir a correção.',bad:'Verificador com falha',good:'Verificador corrigido',failed:['$ python verificar.py','Esperado: receita_centavos = 12950','Recebido: 15450','Falha: uma venda repetida entrou na soma.'],passed:['$ python verificar.py','3 vendas aceitas · 3 rejeitadas','receita_centavos = 12950','Concluído: PASSOU — resultado do exemplo conferido.'],fix:'Compare o contrato, retire o registro repetido e execute o teste novamente. Não altere o gabarito.'},
 mcp:{title:'Painel de conexão',prompt:'Conectar e consultar são duas verificações diferentes.',bad:'Conexão indisponível',good:'Consulta válida',failed:['Cliente → datano-sample','Servidor indisponível: caminho do executável não encontrado.','Falha: nenhuma ferramenta foi consultada.'],passed:['Cliente → datano-sample: conectado','Ferramentas da amostra localizadas','Consulta → resposta estruturada do exemplo','Concluído: conexão e resposta conferidas neste exercício.'],fix:'Confira o caminho absoluto, o executável e o servidor ativo. Depois faça uma consulta com entrada conhecida.'}
};
let simulatorId=0;
class LearningSimulation extends HTMLElement{
 connectedCallback(){if(this.dataset.mounted)return;this.dataset.mounted='true';const s=scenarios[this.getAttribute('scenario')]||scenarios.brief;const id='learning-sim-'+(++simulatorId);this.innerHTML=`<section class="learning-simulator" aria-labelledby="${id}"><div class="sim-chrome"><span aria-hidden="true">● ● ●</span><strong id="${id}">${s.title}</strong><span>SIMULAÇÃO</span></div><div class="sim-body"><p>${s.prompt}</p><p class="sim-note">Exercício no navegador: respostas prontas, sem executar comandos nem conectar sua IA.</p><fieldset><legend>Escolha o cenário para experimentar</legend><label><input type="radio" name="${id}-case" value="bad" checked>${s.bad}</label><label><input type="radio" name="${id}-case" value="good">${s.good}</label></fieldset><div class="sim-actions"><button type="button" class="button ghost" data-sim-run>Executar simulação →</button><button type="button" class="button ghost" data-sim-fix hidden>Ver como corrigir</button><button type="button" class="button ghost" data-sim-retry hidden>Tentar novamente</button></div><pre data-sim-output role="status" aria-live="polite">Pronto para praticar. Experimente uma falha e depois a correção.</pre></div></section>`;
 this.attempts=0;this.addEventListener('click',e=>{if(e.target.closest('[data-sim-run]')||e.target.closest('[data-sim-retry]'))this.run(s);if(e.target.closest('[data-sim-fix]')){this.querySelector('[data-sim-output]').textContent=s.fix;this.querySelector('input[value="good"]').checked=true;this.querySelector('[data-sim-retry]').hidden=false;}});
 }
 disconnectedCallback(){clearTimeout(this.timer);}
 run(s){clearTimeout(this.timer);const good=this.querySelector('input:checked').value==='good',output=this.querySelector('[data-sim-output]'),button=this.querySelector('[data-sim-run]');button.disabled=true;output.textContent='Simulando os passos…';this.dataset.state='in_progress';this.querySelector('[data-sim-fix]').hidden=true;this.querySelector('[data-sim-retry]').hidden=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.timer=setTimeout(()=>{output.textContent=(good?s.passed:s.failed).join('\n');this.dataset.state=good?'success':'failed';button.disabled=false;this.querySelector('[data-sim-fix]').hidden=good;this.querySelector('[data-sim-retry]').hidden=false;this.attempts++;this.dispatchEvent(new CustomEvent('simulation-result',{bubbles:true,detail:{success:good,scenario:this.getAttribute('scenario')||'brief',attempts:this.attempts}}));},reduced?0:450);}
}
if(!customElements.get('datano-simulation'))customElements.define('datano-simulation',LearningSimulation);
