export const sources = {
  cli: ['Comandos do Codex', 'https://learn.chatgpt.com/docs/developer-commands?surface=cli'],
  ide: ['Codex no editor', 'https://learn.chatgpt.com/docs/codex/ide'],
  start: ['Primeiros passos', 'https://learn.chatgpt.com/docs/quickstart'],
  config: ['Configuração', 'https://learn.chatgpt.com/docs/config-file/config-basic'],
  agents: ['Instruções AGENTS.md', 'https://learn.chatgpt.com/docs/agent-configuration/agents-md'],
  skills: ['Criar skills', 'https://learn.chatgpt.com/docs/build-skills'],
  mcp: ['MCP', 'https://learn.chatgpt.com/docs/extend/mcp?surface=cli'],
  docs: ['MCP de documentação OpenAI', 'https://developers.openai.com/learn/docs-mcp'],
  exec: ['Modo não interativo', 'https://learn.chatgpt.com/docs/non-interactive-mode'],
  goals: ['Goals no Codex', 'https://developers.openai.com/cookbook/examples/codex/using_goals_in_codex'],
  security: ['Permissões e segurança', 'https://learn.chatgpt.com/docs/security'],
  prompts: ['Codex Prompting Guide', 'https://developers.openai.com/cookbook/examples/gpt-5/codex_prompting_guide'],
};
export const tracks = [
  { id: 'fundamentos', name: 'Primeiros passos', level: 'Iniciante', icon: '01', color: 'blue', description: 'Prepare o ambiente e transforme sua primeira ideia em uma tarefa bem definida.' },
  { id: 'editor', name: 'Seu editor, potencializado', level: 'Intermediário', icon: '02', color: 'teal', description: 'Trabalhe com contexto, instruções de projeto e revisões dentro do VS Code.' },
  { id: 'fluxos', name: 'Do pedido à entrega', level: 'Intermediário', icon: '03', color: 'amber', description: 'Depure, teste e refatore com um processo que você consegue verificar.' },
  { id: 'avancado', name: 'Além do básico', level: 'Avançado', icon: '04', color: 'violet', description: 'Conecte ferramentas, crie skills e automatize tarefas reproduzíveis.' },
];
const lesson = (id, track, title, minutes, summary, sections, code, exercise, question, choices, correct, explanation, refs) => ({ id, track, title, minutes, summary, sections, code, exercise, quiz: { question, choices, correct, explanation }, refs });
export const lessons = [
  lesson('entenda', 'fundamentos', 'Conheça seu parceiro de código', 8, 'Entenda o ciclo de trabalho e escolha onde começar.', [
    ['O que você vai aprender', 'Codex ajuda a explorar projetos, implementar mudanças e verificar resultados. No editor, o código e a conversa ficam próximos. No terminal, você trabalha a partir de uma pasta. Comece em um projeto de estudo que possa alterar.'],
    ['Seu primeiro fluxo', 'Use este ciclo da Academy: observar → definir → executar → verificar. Primeiro descubra o entrypoint e os comandos do projeto. Depois peça uma mudança pequena. Leia o diff e execute a validação antes de considerar a tarefa concluída.'],
    ['Uma entrega que dá para conferir', '“Melhore o site” deixa o resultado em aberto. Prefira: “Adicione um estado vazio à lista, preservando a API, e mostre como verificar”. Registre o comportamento esperado e o limite da mudança.']
  ], 'codex "Explique a estrutura deste projeto e indique como executar os testes. Não altere arquivos."', 'Escolha um projeto de estudo e peça um mapa com entrypoint, dependências e um comando de validação. Confira os três itens nos arquivos.', 'O que torna uma primeira tarefa verificável?', ['Um objetivo pequeno e um critério de aceitação', 'Pedir mudanças em todos os arquivos', 'Aceitar qualquer resposta sem ler o diff'], 0, 'Um resultado observável permite comparar o pedido com a entrega.', ['start']),
  lesson('instalacao', 'fundamentos', 'Instale e faça seu primeiro login', 12, 'CLI, extensão e uma checagem simples do ambiente.', [
    ['Prepare o ambiente', 'Para instalar pelo npm, tenha Node.js e npm disponíveis. No VS Code desktop, procure a extensão oficial Codex, publicada pela OpenAI, e confira o publicador antes de instalar. O portal oferece um atalho na área VS Code.'],
    ['Faça a verificação', 'No terminal integrado, execute os comandos abaixo. A instalação global altera suas ferramentas locais; use uma máquina em que você possa instalar programas. Abra a pasta do projeto antes de começar a sessão.'],
    ['Autenticação', 'Siga o fluxo de login apresentado pelo Codex. Acesso e limites dependem da conta e da configuração da organização. Não copie credenciais para o projeto. Se o comando não for encontrado, reabra o terminal e confira o PATH do npm.']
  ], 'npm install -g @openai/codex\ncodex --version\ncodex login\ncodex', 'Instale a extensão oficial, autentique e peça apenas uma explicação do README. Compare a resposta com o arquivo.', 'Onde você deve colocar credenciais de login?', ['No README público', 'No fluxo de autenticação oficial', 'Em um comentário do código'], 1, 'Use o mecanismo de autenticação da ferramenta; arquivos públicos não armazenam credenciais.', ['start', 'ide']),
  lesson('prompt', 'fundamentos', 'Escreva pedidos que chegam a um resultado', 10, 'Objetivo, contexto, limites e evidência de conclusão.', [
    ['Quatro peças para começar', 'Nossa receita de tarefa: diga o objetivo, aponte o contexto, fixe limites e descreva a validação. Nomeie o componente relevante. Se não souber o arquivo, peça que Codex o localize e explique o caminho antes de editar.'],
    ['Dê evidência útil', 'Inclua passos de reprodução e a mensagem de erro sem dados sensíveis. Para uma tela, descreva o estado atual e o esperado. Para uma função, ofereça um exemplo de entrada e saída. Evite esconder o requisito em uma longa história.'],
    ['Trabalhe em etapas', 'Para uma mudança grande, solicite um plano e checkpoints. Quando o resultado estiver parcial, explique a diferença com um exemplo concreto. O Estúdio de prompts gera um ponto de partida que você pode adaptar.']
  ], 'Objetivo: corrigir o filtro de produtos.\nContexto: src/catalogo.js; busca com acentos falha.\nLimites: preservar formato da API e dados originais.\nAceite: buscar "cafe" encontra "Café".\nValidação: reproduzir a falha, corrigir e testar o caso.', 'No Estúdio, monte uma tarefa sua. Antes de enviar, identifique um resultado que possa observar na interface ou em um teste.', 'Qual contexto ajuda mais a corrigir um bug?', ['“Está ruim”', 'Uma lista de elogios ao projeto', 'Passos de reprodução e resultado esperado'], 2, 'Reprodução e resultado esperado reduzem ambiguidade.', ['prompts']),
  lesson('terminal', 'fundamentos', 'Comandos e sessões sem mistério', 10, 'Separe comandos do shell e comandos da conversa.', [
    ['Dois lugares diferentes', 'Execute codex e seus subcomandos no terminal. Use comandos com barra dentro da conversa do Codex. Digitar /plan no PowerShell não inicia o modo de planejamento. O laboratório mostra a diferença com respostas simuladas.'],
    ['Explore a sessão', 'Use /plan para elaborar um caminho e /diff para examinar mudanças. Consulte /status para o estado da sessão. O menu aberto por / é a referência da superfície instalada; disponibilidade pode variar entre CLI, IDE e app.'],
    ['Retome com contexto', 'codex resume abre a seleção de sessões. Com --last, retoma a última. Confira a pasta e o estado do Git antes de continuar: arquivos podem ter mudado desde a conversa anterior.']
  ], 'codex --help\ncodex resume\ncodex resume --last', 'No laboratório, tente /plan e codex --version. Depois encontre a mesma ajuda no terminal real.', 'Onde executar /plan?', ['Na conversa do Codex', 'Na barra de endereço do navegador', 'Como comando do sistema operacional'], 0, 'Slash commands pertencem ao compositor do Codex.', ['cli']),
  lesson('contexto', 'editor', 'Leve o contexto do VS Code para a tarefa', 12, 'Arquivo aberto, seleção e revisão no lugar certo.', [
    ['Abra o projeto inteiro', 'No VS Code desktop, abra a pasta raiz do repositório. Localize o arquivo envolvido e selecione o trecho que precisa de atenção. A extensão pode trazer arquivos abertos e seleções para a conversa; confira o contexto exibido antes de enviar.'],
    ['Faça uma pergunta localizada', 'Exemplo da Academy: selecione uma função que formata datas e peça uma explicação de seus casos limite. Depois envie uma entrada inválida e solicite um comportamento consistente. Preserve o contrato da função.'],
    ['Confira a edição', 'Leia os trechos alterados no editor e os demais arquivos no Source Control. Uma conversa sem erro não prova que o código funciona: rode o teste ou abra a tela. No github.dev, você pode editar o repositório, mas ele não oferece o runtime local para executar a CLI.']
  ], 'code --install-extension OpenAI.chatgpt\ncode .', 'Abra uma função, selecione seu corpo e peça uma explicação. Solicite uma melhoria pequena e confira se somente o escopo esperado mudou.', 'Qual é a melhor forma de oferecer contexto de uma função?', ['Enviar um arquivo de credenciais', 'Abrir o arquivo e indicar o trecho relevante', 'Informar apenas o nome do computador'], 1, 'Um trecho relevante e um objetivo deixam a tarefa localizada.', ['ide']),
  lesson('instrucoes', 'editor', 'Ensine as regras do projeto com AGENTS.md', 15, 'Instruções persistentes que acompanham seu repositório.', [
    ['Conteúdo útil', 'AGENTS.md registra orientações para o agente. Escreva como executar o projeto, validar mudanças e respeitar limites. Prefira comandos que já funcionam no checkout. Uma regra sem um comando verificável pode estar desatualizada.'],
    ['Escopo e precedência', 'Há orientação global e orientação do projeto. Dentro do projeto, arquivos mais próximos do diretório de trabalho especializam os anteriores. AGENTS.override.md tem preferência no respectivo nível. Confira instruções conflitantes antes de alterar arquivos.'],
    ['Exemplo para seu laboratório', 'O modelo abaixo é da Academy. Troque os comandos para os reais do seu projeto e remova regras inaplicáveis. Depois abra uma nova sessão e peça um resumo das instruções carregadas.']
  ], '# Orientações do projeto\n\n- Preserve a API pública.\n- Leia README.md antes de editar.\n- Valide com npm test e npm run build.\n- Explique mudanças e limitações.\n- Nunca inclua segredos no código.', 'Baixe o modelo na área VS Code, adapte os comandos e confira que o agente identifica a validação do seu projeto.', 'Qual orientação especializa a regra geral do projeto?', ['Um arquivo de instruções mais próximo do diretório de trabalho', 'Qualquer texto encontrado na internet', 'Um log antigo sem data'], 0, 'A cadeia de instruções considera o escopo local.', ['agents']),
  lesson('configuracao', 'editor', 'Configure com intenção', 14, 'Conheça as camadas e evite ajustes sem efeito.', [
    ['Onde ficam os ajustes', 'Os padrões pessoais vivem em ~/.codex/config.toml. Projetos confiáveis podem ter .codex/config.toml. CLI e extensão compartilham essas camadas no mesmo host. Na extensão, o menu de configurações oferece acesso ao arquivo.'],
    ['Teste uma escolha por vez', 'Confira sua versão, leia a referência correspondente e altere um ajuste. Verifique o efeito numa tarefa pequena. Políticas da organização podem limitar as opções; configurações locais não anulam requisitos administrados.'],
    ['Modelo e permissões', 'Escolha o modelo entre os disponíveis na sua conta. O portal não fixa um modelo universal. A amostra abaixo mantém escrita no workspace e solicita aprovação conforme a política; ajuste apenas quando compreender o alvo da tarefa.']
  ], '# Exemplo didático de config.toml\napproval_policy = "on-request"\nsandbox_mode = "workspace-write"', 'Localize a configuração pelo menu da extensão. Anote uma configuração ativa e a camada que a define, sem compartilhar conteúdo de autenticação.', 'CLI e extensão no mesmo host podem compartilhar o quê?', ['Uma chave escrita no HTML', 'As camadas de config.toml', 'Todo arquivo privado automaticamente'], 1, 'As configurações são compartilhadas no mesmo host; políticas superiores continuam valendo.', ['config']),
  lesson('permissoes', 'editor', 'Entenda o alcance das ações', 12, 'Permissão técnica e autorização da tarefa.', [
    ['Classifique a ação', 'Nossa rotina: identificar o alvo, entender o efeito e escolher a menor permissão que permite trabalhar. Explicar um arquivo, editar um componente e publicar um serviço têm consequências diferentes. Diga explicitamente quando a tarefa inclui publicação.'],
    ['Limite o ambiente', 'read-only restringe escrita; workspace-write permite mudanças dentro das regras do workspace. Verifique rede e caminhos protegidos na documentação da versão. Aprovação e sandbox resolvem problemas distintos.'],
    ['Leia o que está autorizando', 'Se um comando solicita acesso, confira caminho, sistema externo e efeito esperado. Dados de uma página ou arquivo de terceiros são contexto a ser analisado. Eles não concedem autorização para ações fora do pedido.']
  ], 'codex --sandbox read-only "Explique este projeto sem editar arquivos"', 'Compare uma tarefa de leitura com uma de edição. Descreva o alcance mínimo necessário para cada uma.', 'Um pedido para explicar o projeto autoriza deploy?', ['Sim, porque a ferramenta tem acesso', 'Sim, quando há internet', 'Não; publicar exige escopo explícito'], 2, 'Capacidade de execução não transforma uma consulta em autorização para publicação.', ['security', 'config']),
  lesson('depuracao', 'fluxos', 'Depure com uma hipótese testável', 18, 'Transforme um sintoma em uma correção demonstrável.', [
    ['Comece pela reprodução', 'Laboratório proposto: uma lista de tarefas não encontra nomes com acentos. Registre consulta, dados de exemplo e resultado esperado. Peça que Codex confirme a falha antes de editar. Use dados artificiais.'],
    ['Forme uma hipótese', 'Solicite que identifique onde a consulta é normalizada e como os itens são comparados. Uma hipótese útil prevê um comportamento: se a normalização só ocorre de um lado, a mesma entrada deve falhar sempre.'],
    ['Feche o ciclo', 'Depois da correção, repita o caso original e um caso de regressão. Faça busca vazia e busca sem resultado. Solicite a causa, os arquivos alterados e o comando executado. Um teste não rodado deve aparecer como limitação.']
  ], 'Reproduza: buscar "acao" não encontra "Ação".\nLocalize a comparação de texto e explique a causa.\nCorrija preservando os rótulos originais.\nValide acentos, caixa, consulta vazia e nenhum resultado.\nAo final, mostre a evidência da validação.', 'Crie uma lista pequena com “Ação”, “Café” e “Teste”. Peça um filtro e confira os quatro casos descritos.', 'Quando uma correção está demonstrada?', ['Quando elimina a falha reproduzida e passa pelos casos relevantes', 'Quando a resposta diz “resolvido”', 'Quando o código ficou maior'], 0, 'Reprodução e regressão permitem verificar o comportamento.', ['ide', 'prompts']),
  lesson('testes', 'fluxos', 'Peça testes que verificam comportamento', 16, 'Cenários relevantes, limites e comandos reais.', [
    ['Defina o contrato', 'Exercício da Academy: uma função recebe preço e quantidade e calcula o total. Especifique o que acontece com quantidade zero, valor negativo e entrada inválida. Sem semântica definida, um teste pode validar o comportamento errado.'],
    ['Use o ambiente do projeto', 'Peça ao agente que identifique o framework e o comando canônico antes de criar testes. Evite acrescentar dependências apenas para testar uma alteração simples. Comece pelo teste do componente e amplie conforme o risco.'],
    ['Leia a evidência', 'Confira se os testes foram executados e se falhariam antes da correção. Para uma tela, acrescente uma interação no navegador. Para uma API, confira respostas e erros. Um teste que repete o código não oferece uma verificação independente.']
  ], 'Identifique o runner de testes deste repositório.\nPara a função calcularTotal, cubra os contratos descritos no README.\nInclua caso normal, zero e entrada inválida.\nExecute os testes e informe comando, resultado e limites.', 'Escolha uma função pequena e escreva três exemplos de entrada e saída antes de pedir os testes.', 'Qual teste é mais útil?', ['Um teste que só confirma que a função existe', 'Um teste de comportamento com entrada e saída esperada', 'Um teste que copia toda a implementação'], 1, 'Um contrato externo ajuda a detectar regressões.', ['prompts']),
  lesson('revisao', 'fluxos', 'Revise e refatore sem perder o contrato', 18, 'Mudanças pequenas e comparação antes/depois.', [
    ['Peça uma revisão focalizada', 'Escolha um critério: correção, acessibilidade, desempenho ou compatibilidade. Solicite achados com arquivo, cenário e impacto. Uma lista de preferências de estilo não substitui evidência de um problema.'],
    ['Refatore em passos', 'No exercício, extraia a normalização de busca para uma função, preservando o resultado. Execute a mesma coleção de entradas antes e depois. Se o pedido alterar o comportamento, descreva a migração de forma explícita.'],
    ['Prepare a entrega', 'Confira git diff --check e o diff completo. Observe arquivos não rastreados. Registre testes e limitações. Commit e publicação devem acompanhar o escopo autorizado, e você deve conferir a mudança antes de compartilhar.']
  ], 'git status --short --branch\ngit diff --check\ngit diff\ncodex review --uncommitted', 'Faça uma refatoração pequena e compare entradas e saídas. Peça a revisão das mudanças ainda não commitadas.', 'O que uma refatoração deve preservar por padrão?', ['O comportamento e a API existentes', 'Toda duplicação, obrigatoriamente', 'Qualquer bug, sem análise'], 0, 'A mudança estrutural preserva o contrato, salvo solicitação de alteração funcional.', ['cli', 'prompts']),
  lesson('projeto', 'fluxos', 'Projeto guiado: sua primeira entrega', 30, 'Construa uma lista de tarefas acessível e verificável.', [
    ['Briefing do projeto', 'Crie uma aplicação de estudo com adicionar, concluir e filtrar tarefas. Use dados locais e nomes artificiais. O objetivo é praticar o fluxo inteiro. Defina o aceite: não permitir rótulo vazio, preservar tarefas após recarregar e operar com teclado.'],
    ['Milestones da Academy', '1. Peça um plano e escolha a implementação mais simples. 2. Construa adicionar e concluir. 3. Inclua persistência e filtro. 4. Verifique estados vazios, navegação por teclado e recarga. Revise cada etapa antes de continuar.'],
    ['Uma conclusão honesta', 'No relatório final, inclua requisitos atendidos e evidências. Se o ambiente não permitir teste no navegador, registre a lacuna. Publique somente depois de revisar os arquivos e confirmar que publicação está no pedido.']
  ], '/plan Crie uma lista de tarefas para estudo com adicionar, concluir, filtrar e persistir localmente. Proponha etapas pequenas e validação por teclado, dados vazios e recarga. Aguarde minha escolha da abordagem antes de implementar.', 'Execute o projeto numa pasta de estudo pelo VS Code. Salve screenshots e um checklist dos cenários verificados.', 'Qual conjunto demonstra a entrega?', ['Uma promessa de que tudo funciona', 'Só a contagem de arquivos', 'Requisitos atendidos, diff revisado e cenários verificados'], 2, 'O checklist relaciona o objetivo com a evidência do resultado.', ['prompts', 'goals']),
  lesson('mcp', 'avancado', 'Conecte conhecimento com MCP', 18, 'Configure uma integração de documentação e confira seu alcance.', [
    ['Conexão com ferramentas', 'MCP fornece ferramentas e contexto a clientes como Codex. Servidores locais podem usar STDIO; servidores remotos podem usar HTTP. A configuração no mesmo host é compartilhada pela CLI e extensão.'],
    ['Comece com documentação', 'O servidor oficial OpenAI abaixo permite consultar documentação. Ele é de leitura e não chama a API em seu nome. Registre-o e confira a lista. Em seguida peça a fonte oficial de uma dúvida específica.'],
    ['Avalie outras integrações', 'Antes de conectar um servidor, confira origem, transporte, credenciais e ferramentas expostas. No exercício, mantenha a tarefa restrita à consulta. Uma integração capaz de escrever num sistema precisa de um pedido que autorize a ação.']
  ], 'codex mcp add openaiDeveloperDocs --url https://developers.openai.com/mcp\ncodex mcp list', 'Configure o MCP oficial de docs e solicite uma referência sobre config.toml. Abra a fonte retornada e compare a afirmação.', 'O MCP oficial de documentação realiza chamadas da API em seu nome?', ['Não; fornece acesso de leitura à documentação', 'Sim, qualquer operação financeira', 'Sim, sem autenticação ou limite'], 0, 'O servidor de docs fornece conhecimento, não execução de API.', ['mcp', 'docs']),
  lesson('skills', 'avancado', 'Transforme uma rotina em skill', 20, 'Instruções reutilizáveis com gatilho e resultado definidos.', [
    ['Escolha uma rotina', 'Skills agrupam orientações e recursos para tarefas recorrentes. Comece com uma atividade delimitada: revisar documentação do projeto e conferir comandos. Diferencie instruções do repositório, em AGENTS.md, de um fluxo reutilizável.'],
    ['Descreva o contrato', 'No SKILL.md, forneça nome, descrição e etapas. A descrição deve explicar quando usar. Recursos e scripts opcionais devem ter função clara. Use o criador de skills disponível no seu cliente para definir o local e validar o pacote.'],
    ['Experimente antes de distribuir', 'Teste com uma tarefa que deve ativar a skill e outra em que ela não se aplica. Verifique se o resultado inclui evidência. Se quiser distribuir, consulte o fluxo de plugins da documentação da versão.']
  ], '---\nname: revisar-documentacao\ndescription: Conferir documentação e comandos de um projeto antes de uma entrega.\n---\n\n1. Leia o README e o manifesto.\n2. Confira os comandos documentados.\n3. Reporte divergências com arquivo e evidência.\n4. Altere somente o escopo solicitado.', 'Use o criador de skills para montar esta rotina. Valide o gatilho, uma execução de estudo e uma tarefa sem relação com documentação.', 'O que ajuda a skill a ser usada no momento adequado?', ['Uma descrição clara de quando usar', 'Um nome aleatório e nada mais', 'Credenciais colocadas no SKILL.md'], 0, 'A descrição comunica o gatilho; as etapas definem o fluxo.', ['skills']),
  lesson('automacao', 'avancado', 'Automatize tarefas com codex exec', 22, 'Saída estruturada e permissões explícitas em scripts.', [
    ['Da conversa para um comando', 'codex exec executa uma tarefa sem a interface interativa. Use em análises reproduzíveis e scripts. O comando pode emitir eventos JSONL e salvar a mensagem final em arquivo. Escolha um trabalho de leitura para a primeira experiência.'],
    ['Inspecione o resultado', 'No exercício, gere um resumo de riscos do projeto. Leia o relatório e confira cada caminho citado. Um processo pode terminar sem erro e ainda produzir uma análise incompleta; validação precisa incluir conteúdo e estrutura.'],
    ['Automação com controle', 'Para tarefas que editam, configure o sandbox necessário e valide o diff gerado. Em CI, siga a orientação oficial de autenticação e mantenha credenciais fora de jobs que executam código não confiável. O site não armazena chaves nem executa agentes remotos.']
  ], 'codex exec --sandbox read-only --json -o resumo.md "Analise a estrutura deste projeto e liste riscos com caminhos e evidências. Não altere o código."', 'Execute o comando em um repositório de estudo e confira dois caminhos do relatório. Não publique o relatório se ele contiver informações privadas.', 'Como obter eventos legíveis por ferramentas?', ['Com --json, que emite JSONL', 'Fazendo screenshot do terminal', 'Removendo todas as permissões'], 0, 'JSONL representa eventos em registros separados por linha.', ['exec']),
  lesson('goals', 'avancado', 'Conduza tarefas longas com checkpoints', 20, 'Uma meta concreta, métricas e critérios de encerramento.', [
    ['Defina a linha de chegada', 'Goals acompanham um resultado persistente no Codex. A funcionalidade está documentada a partir da CLI 0.128.0; confira a disponibilidade no seu cliente. Use uma meta observável quando o caminho exigir investigação.'],
    ['Exemplo da Academy', 'Em vez de “deixe rápido”, use “reduza a busca da lista de estudo para menos de 100 ms com 10 mil itens artificiais, preservando os resultados”. Meça uma baseline no mesmo ambiente e mantenha casos de correção.'],
    ['Pare com evidência', 'Defina checkpoints, limites de escopo e quando pedir uma decisão. Revise resultado e métricas antes de concluir. Pause ou retome a meta pelo comando disponível. Goals não substituem sua revisão nem tornam publicação automática.']
  ], '/goal Reduza o tempo de busca para menos de 100 ms em 10 mil itens de estudo, preservando os resultados e documentando baseline e validação.\n/goal pause\n/goal resume', 'Escreva uma meta com métrica, dataset artificial, ambiente e critério de aceite. Peça a baseline antes da mudança.', 'Uma boa meta longa contém o quê?', ['Uma palavra genérica', 'Resultado mensurável e critério de conclusão', 'Permissão irrestrita para qualquer sistema'], 1, 'A linha de chegada mensurável permite acompanhar e encerrar o trabalho.', ['goals']),
];
const c = (command, title, category, where, description) => ({ command, title, category, where, description });
export const commands = [
  c('npm install -g @openai/codex', 'Instalar CLI', 'Ambiente', 'Terminal', 'Instala a ferramenta; requer Node.js/npm.'),
  c('code --install-extension OpenAI.chatgpt', 'Instalar extensão oficial', 'Ambiente', 'Terminal', 'Requer o comando code do VS Code desktop.'),
  c('code .', 'Abrir a pasta no VS Code', 'Ambiente', 'Terminal', 'Abra a raiz do projeto.'),
  c('codex --version', 'Verificar versão', 'Ambiente', 'Terminal', 'Compare com a documentação instalada.'),
  c('codex --help', 'Consultar ajuda', 'Ambiente', 'Terminal', 'Referência da CLI local.'),
  c('codex login', 'Autenticar', 'Ambiente', 'Terminal', 'Segue o fluxo de login.'),
  c('codex', 'Iniciar sessão', 'Sessões', 'Terminal', 'Inicie dentro do projeto.'),
  c('codex resume --last', 'Retomar última sessão', 'Sessões', 'Terminal', 'Confira pasta e Git antes de continuar.'),
  c('codex fork', 'Ramificar uma sessão', 'Sessões', 'Terminal', 'Explore outro caminho a partir de uma conversa.'),
  c('/plan', 'Planejar', 'Conversa', 'Codex CLI', 'Elabora o caminho antes de implementar.'),
  c('/status', 'Consultar estado', 'Conversa', 'Codex CLI', 'Veja contexto e estado da sessão.'),
  c('/model', 'Escolher modelo', 'Conversa', 'Codex CLI', 'Use o catálogo disponível na conta.'),
  c('/permissions', 'Consultar permissões', 'Conversa', 'Codex CLI', 'Ajuste o alcance das ações.'),
  c('/diff', 'Examinar alterações', 'Conversa', 'Codex CLI', 'Confira o diff gerado.'),
  c('/compact', 'Resumir contexto', 'Conversa', 'Codex CLI', 'Compacta uma conversa longa.'),
  c('/init', 'Criar instruções', 'Conversa', 'Codex CLI', 'Gera base para AGENTS.md; revise.'),
  c('/mcp', 'Inspecionar integrações', 'Integrações', 'Codex CLI', 'Lista servidores e ferramentas.'),
  c('/skills', 'Explorar skills', 'Integrações', 'Codex CLI', 'Selecione fluxos reutilizáveis.'),
  c('/plugins', 'Explorar plugins', 'Integrações', 'Codex CLI', 'Verifique permissões antes de instalar.'),
  c('/goal', 'Gerenciar meta', 'Conversa', 'Codex CLI', 'Consulte a meta persistente.'),
  c('/goal pause', 'Pausar meta', 'Conversa', 'Codex CLI', 'Interrompe o acompanhamento ativo.'),
  c('/goal resume', 'Retomar meta', 'Conversa', 'Codex CLI', 'Continua a meta pausada.'),
  c('/exit', 'Encerrar sessão', 'Sessões', 'Codex CLI', 'Sai da interface de terminal.'),
  c('codex mcp add openaiDeveloperDocs --url https://developers.openai.com/mcp', 'Adicionar docs oficiais', 'Integrações', 'Terminal', 'Servidor público de documentação.'),
  c('codex mcp list', 'Listar MCPs', 'Integrações', 'Terminal', 'Confira servidores configurados.'),
  c('codex --sandbox read-only', 'Iniciar em leitura', 'Permissões', 'Terminal', 'Limita a escrita no ambiente.'),
  c('codex --sandbox workspace-write', 'Escrever no workspace', 'Permissões', 'Terminal', 'Acesso conforme regras do workspace.'),
  c('codex review --uncommitted', 'Revisar trabalho atual', 'Revisão', 'Terminal', 'Analisa mudanças sem commit.'),
  c('codex exec --json "Resuma a arquitetura"', 'Executar com eventos', 'Automação', 'Terminal', 'Emite eventos JSONL.'),
  c('codex exec -o resumo.md "Resuma o projeto"', 'Salvar resposta final', 'Automação', 'Terminal', 'Escreve a mensagem final em arquivo.'),
  c('git status --short --branch', 'Conferir checkout', 'Revisão', 'Terminal', 'Mostra branch e alterações.'),
  c('git diff --check', 'Verificar diff', 'Revisão', 'Terminal', 'Detecta erros de whitespace.'),
];
export const promptTemplates = {
  implementar: { objective: 'Adicionar um estado vazio acessível à lista de tarefas', context: 'Componente de lista e estilos existentes', constraints: 'Preservar API, identidade visual e navegação por teclado', validation: 'Lista vazia, lista com itens e teste de teclado' },
  depurar: { objective: 'Corrigir a busca que não encontra palavras com acentos', context: 'Filtro de texto; "acao" deve encontrar "Ação"', constraints: 'Preservar rótulos e dados originais; alteração pequena', validation: 'Reproduzir antes; testar acentos, caixa e busca vazia' },
  revisar: { objective: 'Revisar o diff quanto a bugs e regressões', context: 'Mudanças locais ainda não commitadas', constraints: 'Priorizar achados verificáveis; não editar arquivos', validation: 'Cada achado inclui arquivo, cenário, impacto e sugestão' },
  documentar: { objective: 'Atualizar instruções para rodar este projeto', context: 'README, manifesto e scripts de desenvolvimento', constraints: 'Usar comandos reais; não inventar funcionalidades', validation: 'Conferir instalação, execução e testes no checkout' },
};
